## The following functions help to save some computational power
## using lexical scoping by caching the value of a matrix operation 
## (the inverse of a matrix) 

## The first of them, named makeCacheMatrix creates a list of 4 functions
## and has as input an invertible square matrix.
## The functions in this list are: set, get, setinverse and getinverse

makeCacheMatrix <- function(x = matrix()) {
 m <<- NULL
  set <- function(y) {
    x <<- y
    m <<- NULL
  }
  get <- function() x
  setinverse <- function(solve) m <<- solve
  getinverse <- function() m
  list(set = set, get = get,
       setinverse = setinverse,
       getinverse = getinverse)
}


## The last function, named cacheSolve, has as input an invertible
## square matrix, and gives a output the inverse matrix, calculating it
## from scratch if is the first time this function is used, or , otherwise, just
## extracting the value from a variable where this was calculated before
## (if this happens, the message "getting cached data" appears).
## This function uses the list of functions generated by makeCacheMatrix.

cacheSolve <- function(x, ...) {
  m <- x$getinverse()
  if(!is.null(m)) {
    message("getting cached data")
    return(m)
  }
  data <- x$get()
  m <- solve(data, ...)
  x$setinverse(m)
  m
}
